version: "2"
services:
    web:
        build: .
        container_name: moodle-web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html:cached
            - /var/tmp:/var/www/moodledata
        depends_on:
            - db
    db:
        image: mariadb:10
        container_name: moodle-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: moodle
            MYSQL_USER: moodle
            MYSQL_PASSWORD: password
